# This is a basic workflow to help you get started with Actions

name: Build Documents

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  doc-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Install FORD
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install pipx gfortran
          pipx install ford
          
      - name: Generate Documents
        run: |
          ford doc.md

      - name: Upload to Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./api-doc

  deploy:
    needs: doc-build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
